# API配置
api:
  base_url: "http://localhost:11434/api"
  timeout: 30

# 迭代配置
iteration:
  default_rounds: 3  # 默认迭代轮数
  system_prompt: "请仔细思考上一轮的回答，并给出改进后的答案以及原因。如果认为已经是最优答案，请直接给出答案。"
  max_rounds: 5  # 最大迭代轮数限制

# 模型默认参数
model_defaults:
  parameters:
    temperature: 0.7
    max_tokens: 2000
